version: "2.15.1"

services:
  frontend_server:
    build: ./client
    image: client_fe
    command: sh -c "yarn install && npm start"
    ports: 
      - '3000:3000'
    working_dir: /client/
    volumes: 
      - ./client/:/client/
    networks:
      - public
      - private

  backend_server:
    build: ./server
    image: server_be
    command: sh -c "yarn install && yarn run start"
    ports: 
      - '3213:3213'
    working_dir: /server
    volumes: 
      - ./server:/server
    environment:
      MYSQL_HOST: mysql_for_rpt
      MYSQL_USER: root
      MYSQL_PASSWORD: "secret"
      MYSQL_DB: rpt
      MYSQL_TCP_PORT: 3313
    networks:
      - public
      - private

  mysql_for_rpt:
    image: mysql:8.0
    volumes:
      - ropadeltour-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: /run/secrets/db-password
      MYSQL_DATABASE: rpt
    ports:
    - 3313:3306
    networks:
      - private

  mogo_for_rpt:
    image: mongo:4.0-xenial  # mongo:4.4.19-rc2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    volumes:
      - ropadeltour-mongo-data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27013:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "secret"
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mogo_for_rpt:27017/

volumes:
  ropadeltour-mysql-data:
  ropadeltour-mongo-data:

networks:
  public:
  private:
  

secrets:
  db-password:
    file: server/config/password.txt