version: '1.0'

services:
  frontend_server:
    image: client_fe
    command: sh -c "yarn install && npm start"
    ports: 
      - '3000:3000'
    working_dir: /client/
    volumes: 
      - ./client/:/client/
    networks:
      - public
      - private

  backend_server:
    image: server_be
    command: sh -c "yarn install && yarn run start"
    ports: 
      - '3213:3213'
    working_dir: /server
    volumes: 
      - ./server:/server
    environment:
      MYSQL_HOST: mysql_for_rpt
      MYSQL_USER: root
      MYSQL_PASSWORD: "secret"
      MYSQL_DB: rpt
      MYSQL_TCP_PORT: 3313
    networks:
      - public
      - private

  mysql_for_rpt:
    image: mysql:8.0
    volumes:
      - ropadeltour-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: /run/secrets/db-password
      MYSQL_DATABASE: rpt
    ports:
    - 3313:3306
    expose:
    - 3313
    networks:
      - private
volumes:
  ropadeltour-mysql-data:
networks:
  public:
  private:

secrets:
  db-password:
    file: server/config/password.txt